name: Release

on:
  workflow_dispatch
permissions:
  contents: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-release
      - name: Setup git
        run: |
          git config --global user.name 'Ashwin Naren'
          git config --global user.email 'arihant2math@users.noreply.github.com'
      - name: Cargo Authentication
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Release
        run: cargo release --execute
